export default {
  BACKGROUND: require('../assets/images/background.jpeg'),
  LOGO: require('../assets/images/logo.png'),
  SYMBOL: require('../assets/images/symbol.png'),
  DEMOIMAGE: require('../assets/images/demoImage.png'),
  DEMOIMAGE_2: require('../assets/images/demoImage2.jpeg'),
  NOIMAGE: require('../assets/images/noImage.jpeg'),
  NOSEARCH: require('../assets/images/noSearch.jpg'),
  NOTFOUND: require('../assets/images/404.png'),
  FORWARD: require('../assets/images/forward.png'),
  BACKWARD: require('../assets/images/backward.png'),
  PLAY: require('../assets/images/play-button.png'),
  PAUSE: require('../assets/images/pause.png'),
  FULLSIZE: require('../assets/images/full-size.png'),
  MINIMIZE: require('../assets/images/minimize.png'),
  MEDIUMVOLUME: require('../assets/images/medium-volume.png'),
  MUTE: require('../assets/images/mute.png'),
  SPEED: require('../assets/images/speedometer.png'),
  LOCK: require('../assets/images/unlock.png'),
  UNLOCK: require('../assets/images/unlocked.png'),
  SUBTITLE: require('../assets/images/subtitle.png'),
};
